import { MD3DarkTheme, MD3LightTheme } from "react-native-paper";

const trackHubDark = {
	...MD3DarkTheme,
	colors: {
		...MD3DarkTheme.colors,
		primary: "#8b7cb8",
		onPrimary: "#ffffff",
		primaryContainer: "#2d2640",
		onPrimaryContainer: "#c4b8e8",
		secondary: "#7a8ba8",
		onSecondary: "#ffffff",
		secondaryContainer: "#242e3d",
		onSecondaryContainer: "#bcc8dc",
		tertiary: "#7a9e7e",
		onTertiary: "#ffffff",
		tertiaryContainer: "#1e2e20",
		onTertiaryContainer: "#bcd4be",
		error: "#c97a7a",
		onError: "#ffffff",
		errorContainer: "#3d2424",
		onErrorContainer: "#f0c8c8",
		background: "#232228",
		onBackground: "#e8e4f0",
		surface: "#2c2b32",
		onSurface: "#e8e4f0",
		surfaceVariant: "#35343e",
		onSurfaceVariant: "#c8c4d4",
		outline: "#5e5c6a",
		outlineVariant: "#3a3942",
		elevation: {
			level0: "#232228",
			level1: "#29282e",
			level2: "#2c2b32",
			level3: "#302f36",
			level4: "#35333c",
			level5: "#3a3942",
		},
		warning: "#c9a050",
		onWarning: "#2a1e08",
		warningContainer: "#3d3018",
		onWarningContainer: "#f0deaa",
	},
};

const trackHubLight = {
	...MD3LightTheme,
	colors: {
		...MD3LightTheme.colors,
		primary: "#7c6db0",
		onPrimary: "#ffffff",
		primaryContainer: "#e8e2f8",
		onPrimaryContainer: "#2d2640",
		secondary: "#6b7d95",
		onSecondary: "#ffffff",
		secondaryContainer: "#dde4f0",
		onSecondaryContainer: "#242e3d",
		tertiary: "#6b8f6e",
		onTertiary: "#ffffff",
		tertiaryContainer: "#dce8dc",
		onTertiaryContainer: "#1e2e20",
		error: "#c06060",
		onError: "#ffffff",
		errorContainer: "#f4dede",
		onErrorContainer: "#3d2424",
		background: "#f6f4f8",
		onBackground: "#2a2630",
		surface: "#ffffff",
		onSurface: "#2a2630",
		surfaceVariant: "#eceaf2",
		onSurfaceVariant: "#5e5a6a",
		outline: "#d2cedb",
		outlineVariant: "#eceaf2",
		elevation: {
			level0: "#f6f4f8",
			level1: "#efedf2",
			level2: "#eceaf2",
			level3: "#e7e5ed",
			level4: "#e2e0e8",
			level5: "#dddbE3",
		},
		warning: "#b88a40",
		onWarning: "#ffffff",
		warningContainer: "#f4ebd8",
		onWarningContainer: "#3d3018",
	},
};

export {
	trackHubDark,
	trackHubDark as nordDark,
	trackHubLight,
	trackHubLight as nordLight,
};
